# This should not be here.
#  -- chris

CFLAGS ?= -O3

build:
	kremlin-gcc $(CFLAGS) test.c -o $(BENCH)

profile:
	./$(BENCH)
	java KremlinProfiler . > profile.txt

clean:
	-rm *.log kremlin.* *.bc *.dot *.graph sregions.txt profile.txt $(BENCH)
