# This should not be here.
#  -- chris

CFLAGS ?= -O3

build:
	kremlin-gcc $(CFLAGS) test.c -o $(BENCH)

run:
	./$(BENCH)

profile:
	kremlin > profile.txt

clean:
	-rm *.log kremlin.* depth-finder.a *.bc *.ll *.dot *.graph sregions.txt profile.txt $(BENCH)
