env = Environment(CCFLAGS = '-O3')
files = ['debug.cpp', 'kremlin.cpp', 'ATable.cpp', 'MemMapAllocator.cpp',
    'CNode.cpp', 'CRegion.cpp', 'CStat.cpp', 'CTree.cpp',
	'MShadowBase.cpp', 'MShadowSkadu.cpp', 'MShadowSTV.cpp', 
	'compression.cpp', 'config.cpp', 'minilzo.cpp', 'mpool.cpp',
    'MShadowStat.cpp', 'MShadowDummy.cpp', 'MShadowCache.cpp',
	'MShadowNullCache.cpp', 'TagVectorCache.cpp', 'TagVectorCacheLine.cpp'
	]
kremlib_dynamic = env.SharedLibrary('kremlin', files)
files.append('arg.cpp')
kremlib_static = env.Library('kremlin', files)
Return('kremlib_static kremlib_dynamic')
