env = Environment(CCFLAGS = '-O3 -std=c++11 -Wno-deprecated')

debug = ARGUMENTS.get('debug', 0)
debug_level = ARGUMENTS.get('debug_level', 0)
if int(debug):
    env.Append(CPPDEFINES = ['KREMLIN_DEBUG',
                             'KREMLIN_DEBUG_LEVEL=' + str(debug_level)])
else:
    env.Append(CPPDEFINES = ['NDEBUG',
                             'KREMLIN_DEBUG_LEVEL=' + str(debug_level)])

files = ['debug.cpp', 'kremlin.cpp', 'MemMapAllocator.cpp',
    'ProfileNode.cpp', 'RegionContexts.cpp', 'ProfileNodeStats.cpp', 
	'ShadowMemory.cpp', 'compression.cpp', 'KremlinConfig.cpp', 'minilzo.cpp', 
    'mpool.cpp', 'MShadowStat.cpp', 'ShadowMemoryCache.cpp',
	'MShadowNullCache.cpp', 'TagVectorCache.cpp', 'TagVectorCacheLine.cpp',
	'Handlers.cpp','TimeTable.cpp', 'LevelTable.cpp'
	]

kremlib_dynamic = env.SharedLibrary('kremlin', files)
files.append('ArgParse.cpp')
kremlib_static = env.Library('kremlin', files)
Return('kremlib_static kremlib_dynamic')
